version: '3.7'

services:
    demo:
        build: .
        image: graphqldemo:0.0.1
        ports:
            - 8081:8080
        depends_on:
            - postgres
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/users

    postgres:
        image: postgres:12.2-alpine
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: users
            POSTGRES_USER: dbUser
            POSTGRES_PASSWORD: secretDbPassword
